language: r
sudo: false
cache: packages
dist: trusty

latex: true

# Required by rsamplestudy dependence
apt_packages:
   - libgsl0-dev

r_github_packages: lgaborini/rsamplestudy

env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

script:
  - |
    travis_wait 80 R CMD build .
    travis_wait 149 R CMD check rstanBF*tar.gz

after_script:
  - tar -ztvf rstanBF_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::codecov()'

after_failure:
  - cat rstanBF.Rcheck/00*

# Compile pkgdown documentation for the master branch
before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    branch: travis-pkgdown


